### ISSUE TITLE
SQL injection vulnerability via `user` query parameter

### ISSUE THREAD

**Issue by 11k** [tenacious210/website#3]
When accessing emote data via the API or browser for a specific user, the supplied query parameter is passed into a backend function and [inserted](https://github.com/tenacious210/website/blob/d72e6724a88142b18931148e9042a7a89a167e26/emotes/db.py#L17) directly into the SQL query string without sanitization.

A vulnerability like this typically allows malicious URLs such as
```
https://tena.dev/emotes?user=%27%3Bupdate%20emotestats%20set%20yee%3D99999%20where%20lower%28username%29%3D%2711k%27%3B%27
```
to manipulate the database freely. The `user` parameter decodes to
```
';update emotestats set yee=99999 where lower(username)='11k';'
```

Fortunately, Python's sqlite3 library [prevents](https://docs.python.org/3/library/sqlite3.html#cursor-objects) the execution of multiple queries at once by raising a `Warning`, so the attack fails.

Regardless, it's standard practice to insert variables into SQL query strings with parameter substitution, as explained [here](https://docs.python.org/3/library/sqlite3.html#sqlite3-placeholders), and that should probably be followed.

Note that `get_emote_top_posters` makes the same mistake, but is less vulnerable because of a [guard clause](https://github.com/tenacious210/website/blob/d72e6724a88142b18931148e9042a7a89a167e26/emotes/db.py#L54-L56) that exits if the argument isn't an emote.

**Comment by tenacious210** [comment]
Thanks for the info! I secured the "user" parameter [here](https://github.com/tenacious210/website/commit/c0d8b044732b96c2f25cda581d483519dba034f9).

I tried implementing the same fix for `get_emote_top_posters`, but it seems that sqlite3 doesn't allow parameterizing things like [column names](https://github.com/tenacious210/website/blob/c0d8b044732b96c2f25cda581d483519dba034f9/emotes/db.py#L60), so I let the guard clause slide for now. Is there a more secure way to do this?

For reference, [here's](https://github.com/tenacious210/get-emote-stats/blob/main/main.py) the script I run to build/update the database.

**Comment by 11k** [comment]
Hmm, in that case I think relying on the guard clause for validation is easiest and works perfectly fine.

**Comment by tenacious210** [comment]
Sounds good, thanks again! :)
